#!/usr/bin/env bash

run_time=15

func() { echo "contents!"; }

start=$SECONDS
count=0
while (( ( $SECONDS - $start ) < $run_time )); do
  var="$(func)"
  count=$(( $count + 1 ))
done
echo "Captured $count in $run_time seconds"

start=$SECONDS
count=0
while (( ( $SECONDS - $start ) < $run_time )); do
  IFS='' read var < <(func)
  count=$(( $count + 1 ))
done
echo "Read $count in $run_time seconds"

