#!/bin/bash

__ps1_style_arrow_module() {
  if __ps1_powerline; then
    echo -n ' '
  else
    echo -n '> '
  fi
}

__ps1_style_arrow_module_end() {
  if __ps1_powerline; then
    echo -n ' '
  else
    echo -n ' >'
  fi
}

__ps1_style_arrow_module_pad() {
  echo -n ' '
}

