#!/bin/bash

__ps1_style_blockarrow_module() {
  if __ps1_powerline; then
    echo -n '{reverse} '
  else
    echo -n '{reverse} '
  fi
}

__ps1_style_blockarrow_module_end() {
  if __ps1_powerline; then
    echo -n ' {/reverse}'
  else
    echo -n ' '
  fi
}

__ps1_style_blockarrow_module_pad() {
  if ! __ps1_powerline; then
    echo -n ' '
  fi
}

