#!/bin/bash

__ps1_style_block_module() {
  if __ps1_unicode; then
    echo -n +reverse "$(printf '\u258F')"
  else
    echo -n +reverse :space
  fi
}

__ps1_style_block_module_end() {
  if __ps1_unicode; then
    echo -n "$(printf '\u2595')"
  else
    echo -n :space
  fi
}

__ps1_style_block_module_pad() {
  if ! __ps1_unicode; then
    echo -n :space
  fi
}

