#!/bin/bash

__ps1_module_error() {
  (( "$PS1_LAST_ERR" )) || return
  __ps1_ansi '{bg:#FF0}'
  if __ps1_unicode; then
    __ps1_ansi "⚠ "
  else
    echo -n 'err'
  fi
  __ps1_ansi '{bg:#000}'
  echo -n " $PS1_LAST_ERR"
  __ps1_ansi_style
}

__ps1_style_default_error() {
  echo -n '{fg:#700}'
}

