#!/bin/bash

red::module::error() {
  (( "$PS1_LAST_ERR" )) || return
  __red_ansi '{bg:#FF0}'
  if __red_unicode; then
    __red_ansi "⚠ "
  else
    echo -n 'err'
  fi
  __red_ansi '{bg:#000}'
  echo -n " $PS1_LAST_ERR"
  __red_ansi_style
}

red::style::error() {
  echo -n '{fg:#700}'
}

