#!/bin/bash

which git &>/dev/null || return 0

__ps1_module_git() {
  out="$(set -o pipefail; git branch 2>/dev/null | grep -F '* ' | cut -c 3-)"
  [[ "$out" ]] || return
  if __ps1_unicode; then
    echo -n "$(printf '\u2325') "
  else
    echo -n 'branch '
  fi
  echo -n "$out"
}

__ps1_style_default_git() {
  echo -n '{fg:cyan}'
}

