#!/bin/bash

which git &>/dev/null || return 0

__ps1_module_git() {
  local out=''
  while read line; do
    [[ "${line:0:1}" == '*' ]] && out="${line:2}" && break
  done < <(git branch)
  [[ "$out" ]] || return
  if __ps1_unicode; then
    echo -n "$(printf '\u2325') "
  else
    echo -n 'branch '
  fi
  echo -n "$out"
}

__ps1_style_default_git() {
  echo -n '{fg:cyan}'
}

