#!/bin/bash

which git &>/dev/null || return 0

red::module::gitbranch() {
  local out=''
  while read line; do
    [[ "${line:0:1}" == '*' ]] && out="${line:2}" && break
  done < <(git branch)
  [[ "$out" ]] || return
  if __red_powerline; then
    echo -n " "
  elif __red_unicode; then
    echo -n "⌥ "
  else
    echo -n 'branch '
  fi
  echo -n "$out"
}

red::style::gitbranch() {
  echo -n '{fg:cyan}'
}

