#!/bin/bash

which kubectl &>/dev/null || return 0

red::module::k8scontext() {
  local out="$(kubectl config current-context 2>/dev/null)"
  [[ "$out" ]] || return
  if __red_unicode; then
    echo -n "☸ "
  else
    echo -n 'k8s '
  fi
  echo -n "$out"
}

red::style::k8scontext() {
  echo -n '{fg:blue}'
}

