#!/bin/bash

red::module::virtualenv() {
  local out="$(basename "$VIRTUAL_ENV" 2>/dev/null)"
  [[ "$out" ]] || return
  if __red_unicode; then
    echo -n "🐍"
  else
    echo -n 'py env '
  fi
  echo -n "$out"
}

red::style::virtualenv() {
  echo -n '{fg:yellow}'
}

