#!/usr/bin/env bash

red::module::virtualenv() {

  IFS='' read -r venv < <(basename "$VITURAL_ENV" 2>/dev/null)

  [[ "$venv" ]] || return

  red::set module_virtualenv_content "$venv"
  red::set module_virtualenv_color '#C90'
  red::set module_virtualenv_prefix_unicode '🐍'
  red::enable module_virtualenv_prefix_unicode_wide
  red::set module_virtualenv_prefix_ascii 'venv'

}

